#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#if defined(HID_BUILD_PROTOTYPE) == defined(HID_BUILD_PCB)
#error "Select exactly one of HID_BUILD_PROTOTYPE or HID_BUILD_PCB"
#endif

#if defined(HID_BUILD_PROTOTYPE)
#define CONTROLLER_USB_SELF_POWERED 1U
#define CONTROLLER_USB_ATTRIBUTES 0xC0U
#define CONTROLLER_USB_PC_MAX_POWER 0U
#define CONTROLLER_USB_SWITCH_MAX_POWER 0U
#else
#define CONTROLLER_USB_SELF_POWERED 0U
#define CONTROLLER_USB_ATTRIBUTES 0x80U
#define CONTROLLER_USB_PC_MAX_POWER 50U
#define CONTROLLER_USB_SWITCH_MAX_POWER 250U
#endif

#endif
